version: "3.8"

services:
  localstack:
    profiles: [infra, all]
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    build:
        context: ../aws/
        dockerfile: ../localstack.Dockerfile
    ports:
      - 4566:4566  # Edge port
      - 4572:4572  # S3 service port
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  # We can use amazon RDS instead of bare postgress, but for the task itself a KV store should be a better fit 
  db:
    profiles: [infra, all]
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ../sql-migrations:/docker-entrypoint-initdb.d

  documents-api:
    profiles: [all]
    container_name: documents-api
    build:
        context: ..
        dockerfile: DocumentStore/Dockerfile
    ports:
      - 80:80