version: "3.8"

services:
  db:
    profiles: [infra, all]
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123!
    ports:
      - 5432:5432
    volumes:
      - ./sql-migrations:/docker-entrypoint-initdb.d # AK TODO maybe it should contain two dots for context

  scheduler-api:
    profiles: [all]
    container_name: scheduler-api
    build:
        context: .. # AK TODO maybe it should contain two dots for context
        dockerfile: SchedulerApi/Dockerfile
    ports:
      - 3000:3000 # AK TODO change to needed for 