version: "3.8"

services:
  db:
    profiles: [infra, all]
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: coding-challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123!
    ports:
      - 5432:5432
    volumes:
      - ../sql-migrations:/docker-entrypoint-initdb.d

  scheduler-api:
    profiles: [all]
    container_name: scheduler-api
    build:
        context: .. 
        dockerfile: SchedulerApi/Dockerfile
    ports:
      - 3000:8080
    depends_on:
      - db